-- MySQL Script generated by MySQL Workbench
-- Mon Jun 24 16:39:24 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `iduser` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NULL,
  `password_hash` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`iduser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`exercises`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`exercises` (
  `idexercises` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `description` TEXT(0) NULL,
  `type` VARCHAR(45) NULL,
  `created_at` VARCHAR(45) NULL,
  `updated_at` VARCHAR(45) NULL,
  PRIMARY KEY (`idexercises`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`sessions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`sessions` (
  `idsessions` INT NOT NULL AUTO_INCREMENT,
  `date` DATE NULL,
  `tempo` VARCHAR(45) NULL,
  `duration` INT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  `users_iduser` INT NOT NULL,
  `exercises_idexercises` INT NOT NULL,
  PRIMARY KEY (`idsessions`, `users_iduser`, `exercises_idexercises`),
  INDEX `fk_sessions_users1_idx` (`users_iduser` ASC) VISIBLE,
  INDEX `fk_sessions_exercises1_idx` (`exercises_idexercises` ASC) VISIBLE,
  CONSTRAINT `fk_sessions_users1`
    FOREIGN KEY (`users_iduser`)
    REFERENCES `mydb`.`users` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sessions_exercises1`
    FOREIGN KEY (`exercises_idexercises`)
    REFERENCES `mydb`.`exercises` (`idexercises`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`progress`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`progress` (
  `idprogress` INT NOT NULL AUTO_INCREMENT,
  `improvement_metric` VARCHAR(45) NULL,
  `value` FLOAT NULL,
  `recorded_at` TIMESTAMP NULL,
  `users_iduser` INT NOT NULL,
  `exercises_idexercises` INT NOT NULL,
  PRIMARY KEY (`idprogress`, `users_iduser`, `exercises_idexercises`),
  INDEX `fk_progress_users1_idx` (`users_iduser` ASC) VISIBLE,
  INDEX `fk_progress_exercises1_idx` (`exercises_idexercises` ASC) VISIBLE,
  CONSTRAINT `fk_progress_users1`
    FOREIGN KEY (`users_iduser`)
    REFERENCES `mydb`.`users` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_progress_exercises1`
    FOREIGN KEY (`exercises_idexercises`)
    REFERENCES `mydb`.`exercises` (`idexercises`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`program`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`program` (
  `idprogram` INT NOT NULL AUTO_INCREMENT,
  `name_program` VARCHAR(45) NULL,
  `description` TEXT(0) NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`idprogram`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`program_sessions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`program_sessions` (
  `idprogram_sessions` INT NOT NULL AUTO_INCREMENT,
  `sessions_idsessions` INT NOT NULL,
  `program_idprogram` INT NOT NULL,
  PRIMARY KEY (`idprogram_sessions`, `sessions_idsessions`, `program_idprogram`),
  INDEX `fk_program_sessions_sessions_idx` (`sessions_idsessions` ASC) VISIBLE,
  INDEX `fk_program_sessions_program1_idx` (`program_idprogram` ASC) VISIBLE,
  CONSTRAINT `fk_program_sessions_sessions`
    FOREIGN KEY (`sessions_idsessions`)
    REFERENCES `mydb`.`sessions` (`idsessions`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_program_sessions_program1`
    FOREIGN KEY (`program_idprogram`)
    REFERENCES `mydb`.`program` (`idprogram`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `mydb` ;

-- -----------------------------------------------------
-- Placeholder table for view `mydb`.`view1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`view1` (`id` INT);

-- -----------------------------------------------------
-- View `mydb`.`view1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`view1`;
USE `mydb`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
